version: '3.3'

networks:
  homeautomation:
  traefik-public:
    external: true
  grafing:
    external: true

services:
  nodered:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

      placement:
        constraints:
          - node.labels.storage==yes
      replicas: 1
      labels:
        - traefik.enable=true
        - "traefik.http.routers.node.rule=Host(`node.${BASE_HOST}`)"
        - "traefik.http.routers.node.entrypoints=websecure"
        - "traefik.http.routers.node.tls.certresolver=le"
        - "traefik.http.routers.node.middlewares=whitelist"
        - "traefik.http.services.node.loadbalancer.server.port=1880"
        - "traefik.http.services.node.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.whitelist.ipwhitelist.sourcerange=192.168.0.0/16"
    image: "nodered/node-red:3.0.2"
    volumes:
      - /docker/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - homeautomation
      - traefik-public
      - grafing
    environment:
      - TZ=Europe/Copenhagen

  dashboard:
    depends_on:
      - nodered
    image: registry.${BASE_HOST}/dashboard
    container_name: dashboard
    networks:
      - traefik-public
    volumes:
      - /docker/dashboard:/data
    environment:
      - BACKEND_MQTT_HOST=mqtt://192.168.3.117
      - BACKEND_OW_KEY=dd93eaf80283929292eac2c8da98e8ce
      - BACKEND_OW_CITYID=2620952
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      labels:
        - traefik.enable=true
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.${BASE_HOST}`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=le"
        - "traefik.http.routers.dashboard.middlewares=whitelist"
        - "traefik.http.services.dashboard.loadbalancer.server.port=5000"
        - "traefik.http.services.dashboard.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.whitelist.ipwhitelist.sourcerange=192.168.0.0/16"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 dashboard
