version: '3.3'

networks: 
  grafing:
    external: true
  traefik-public:
    external: true

services:
  influx:
    image: influxdb:1.6.1
    networks:
      - grafing
    volumes:
      - /glusterfs/influxdb:/var/lib/influxdb 
      - /docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /docker/influxdb/types.db:/usr/share/collectd/types.db:ro
    command: -config /etc/influxdb/influxdb.conf
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

      placement:
        constraints:
          - node.labels.storage==yes
    ports:
      - 25826:25826/udp

  grafana:
    volumes:
      - /docker/grafana:/var/lib/grafana
      - /docker/grafana:/var/log/grafana
    networks:
      - grafing
      - traefik-public
    image: "grafana/grafana"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:graph.${BASE_HOST}
        - traefik.port=3000
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.tags=traefik-public
        - traefik.webservice.frontend.entryPoints=https
