version: '3.3'

services:
  vanilla:
    image: itzg/minecraft-server:java16
    ports:
      - 25565:25565
    volumes:
      - /glusterfs/minecraft/vanilla:/data
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      VERISON: "LATEST"
      MEMORY: 2048M
      ENABLE_AUTOPAUSE: "TRUE"

#  skyfactory4:
#    image: itzg/minecraft-server
#    ports:
#      - 25566:25565
#    volumes:
#      - /glusterfs/minecraft/skyfactory4:/data
#    deploy:
#      placement:
#        constraints:
#          - node.labels.storage==yes
#    environment:
#     EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: "minecraft"
#      RCON_PORT: 25575
#      TYPE: "FORGE"
#      VERSION: "1.12.2"
#      MEMORY: 4G
#      FORGEVERSION: "14.23.5.2838"

  pixelmon:
    image: itzg/minecraft-server:java8
    ports:
      - 25567:25565
    volumes:
      - /glusterfs/minecraft/pixelmon:/data
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      TYPE: "FORGE"
      VERSION: "1.12.2"
      MEMORY: 4G
      FORGEVERSION: "14.23.5.2855"
 

    