version: '3.5'

services:
  traefik:
    image: traefik:v2.1
    command: >
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --certificatesResolvers.sample.acme.email=${ACME_EMAIL}
      --certificatesResolvers.sample.acme.storage=acme.json
      --certificatesResolvers.sample.acme.httpChallenge.entryPoint=web

      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.docker.swarmMode=true
      --providers.docker.exposedByDefault=false
      --providers.docker.network='traefik-public'
      --api.dashboard=true
      --accessLog
      --log.level="DEBUG"
      --api.insecure=true
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
          - node.labels.mysensors == yes
      labels:
        - traefik.http.routers.api.rule=Host(`traefik.juletraesfoden.dk`)
        - traefik.http.routers.api.entrypoints=websecure
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.middlewares=myAuth
        - traefik.http.routers.api.sample
        - traefik.http.middlewares.whitelist.ipwhitelist.sourcerange=192.168.1.7
        - traefik.http.middlewares.myAuth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8383:8080
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/traefik/acme.json:/acme.json
      
networks:
  traefik-public:
    external: true
