version: '3.5'

services:
  traefik:
    image: traefik:v2.1
    command: >
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --certificatesResolvers.le.acme.email=${ACME_EMAIL}
      --certificatesResolvers.le.acme.storage=acme.json
      --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.docker.swarmMode=true
      --providers.docker.exposedByDefault=false
      --providers.docker.network='traefik-public'
      --api
      --log.level="DEBUG"
      --serverstransport.insecureskipverify
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
          - node.labels.mysensors == yes
      labels:
        - "traefik.enable=true"
        # middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
        # global redirect to https
        - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirs.entrypoints=web"
        - "traefik.http.routers.redirs.middlewares=redirect-to-https"

        # Dashboard
        - "traefik.http.routers.api.rule=Host(`traefik.juletraesfoden.dk`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=whitelist"
        - "traefik.http.routers.api.tls.certresolver=le"
        - traefik.http.services.api.loadbalancer.server.port=8080
        - "traefik.http.middlewares.whitelist.ipwhitelist.sourcerange=192.168.0.0/16"
        - "traefik.http.middlewares.myAuth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8383:8080
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/traefik/acme-v2.1.json:/acme.json
      
networks:
  traefik-public:
    external: true
