version: '3.3'

services:
  unifi:
    image: jacobalberty/unifi:latest
    networks:
      - swarm-macvlan1
      - traefik-public
    environment:
      TZ: "Europe/Copenhagen"
      UNIFI_UID: 2000
      UNIFI_GID: 2000
      RUNAS_UID0: 'false'
    volumes:
      - /docker/unifi:/unifi
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
      labels:
        - traefik.enable=true
        - "traefik.http.routers.unifi.rule=Host(`unifi.${BASE_HOST}`)"
        - "traefik.http.routers.unifi.entrypoints=websecure"
        - "traefik.http.routers.unifi.tls.certresolver=le"
        - "traefik.http.routers.unifi.middlewares=unifiwhitelist"
        - "traefik.http.routers.unifi.service=unifi"
        - "traefik.http.services.unifi.loadbalancer.server.port=8443"
        - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
        - "traefik.http.middlewares.unifiwhitelist.ipwhitelist.sourcerange=192.168.0.0/16"

        - "traefik.http.routers.hotspot.rule=Host(`hotspot.${BASE_HOST}`)"
        - "traefik.http.routers.hotspot.entrypoints=websecure"
        - "traefik.http.routers.hotspot.tls.certresolver=le"
        - "traefik.http.routers.hotspot.middlewares=hotspotwhitelist"
        - "traefik.http.routers.hotspot.service=hotspot"
        - "traefik.http.services.hotspot.loadbalancer.server.port=443"
        - "traefik.http.services.hotspot.loadbalancer.server.scheme=https"
        - "traefik.http.middlewares.hotspotwhitelist.ipwhitelist.sourcerange=10.10.10.0/24"
    ports:
      - 8080:8080
      - 8443:8443
      - 3478:3478/udp
      - 6789:6789
      - 10001:10001/udp
      - 1900:1900/udp            

networks:
  traefik-public:
    external: true
  swarm-macvlan1:
    external: true
